[tool.poetry]
name = "video-programmer"
version = "0.1.0"
description = "Video Programmer App"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "*"
uvicorn = {extras = ["standard"], version = "*"}
pydantic-settings = "*"
python-dotenv = "*"
python-dateutil = "*"
pytz = "*"
google-api-python-client = "*"
google-auth = "*"
google-auth-oauthlib = "*"
google-auth-httplib2 = "*"
httpx = "^0.24.0"
pandas = "*"
pytest = "*"
loguru = "*"
sqlalchemy = "*"
alembic = "*"
psycopg2-binary = "*"
authlib = "*"
python-jose = {extras = ["cryptography"], version = "*"}
passlib = {extras = ["bcrypt"], version = "*"}
python-multipart = "*"
starlette = "^0.48.0"

[tool.poetry.group.dev.dependencies]
mypy = "*"
pytest-asyncio = "*"
alembic = "^1.17.0"

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = [
    "tests",
]
asyncio_mode = "auto"